### ISSUE TITLE
Insert secrets into environment variables

### ISSUE THREAD

**Issue by jvisker** [byu-oit/terraform-aws-lambda-api#1]
Should we wire secret permissions into the environment variables to be more the fargate module?

**Comment by joshgubler** [comment]
With Fargate, SSM changes can be pushed to env vars by restarting the task. With Lambda, you would have to redeploy the Lambda. I guess we can make the behavior "close", but we can never make it the same. Should we try to make the contract the same (module mounts env vars) and just document the different behavior?

Are we going to get into trouble trying to get TF to take on more responsibility? In Fargate, ECS actually fetches the SSM param, not TF. With Lambda, TF would have to do it. More inconsistent behavior.
